apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: workshop-cluster-issuer-name
  namespace: workshop
spec:
  acme:
    email: besartshyti@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-secret
    solvers:
      - http01:
          ingress:
            class: traefik