POSTGRES_USER="ab93lka1z1a"
POSTGRES_PASSWORD="bxlao9koslq51"
POSTGRES_HOST="localhost"
POSTGRES_PORT="5432"


psql -U $POSTGRES_USER -h $POSTGRES_HOST -c "CREATE TABLE IF NOT EXISTS fct_prediction (
  id SERIAL PRIMARY KEY,
  img_json JSONB,
  prediction VARCHAR(255),
  label VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);"
