---
- name: Setup k3s agents
  hosts: agents
  vars:
    ansible_ssh_private_key_file: ./k3s_workshop
    ansible_user: root
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

  tasks:
    - name: Retrieve k3s master token
      delegate_to: k3s-workshop-1
      become: true
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    # - name: Print node token
    #   ansible.builtin.debug:
    #     var: node_token.stdout

    - name: Install k3s on agents
      become: true
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars["k3s-workshop-1"]["ansible_host"] }}:6443 K3S_TOKEN={{ node_token["stdout"] }} sh -
